// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhjyyqhwziruolzvffuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoanl5cWh3emlydW9senZmZnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzYyODUsImV4cCI6MjA2NjIxMjI4NX0.k8ezv1ltnQ71p6Q2Gj7AhhPSeV8wQqhLfFewNiK4MuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);